language: java
jdk:
  - openjdk8


sudo: false
install: true

script:
  - cd webapp/CloudCmpting
  - mvn clean install

notifications:
  email:
    recipients:
    - xue.ti@husky.neu.edu
    - chai.yi@husky.neu.edu
    - rui.sun@husky.neu.edu