language: java
jdk:
  - openjdk8


sudo: false
install: true

script:
  - cd webapp/CloudCmpting
  - mvn package
  - cd ../..
  - pwd

notifications:
  email:
    recipients:
    - xue.ti@husky.neu.edu
    - sun.rui@husky.neu.edu
    - chai.yi@husky.edu.edu
