language: java
jdk:
  - openjdk8


sudo: false
install: true

script:
  - pwd
  - cd webapp/CloudCmpting
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
  - cd ../..
  - pwd

notifications:
  email:
    recipients:
    - xue.ti@husky.neu.edu
