language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war
  - ./gradlew build

notifications:
  username:
    recipients:
	-sun.rui@husky.neu.edu
	-xue.ti@husky.neu.edu
	-chai.yi@husky.neu.edu
