language: java
jdk:
  - openjdk8


sudo: false
install: true

script:
  - pwd
  - cd webapp/CloudCmpting
  - mvn package
  - cd ../..
  - pwd


after_sucess:
  - mkdir codedeploy
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip build/libs/ROOT.war infrastruture/aws/codedeploy/appspec.yml
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd
  - cd ..
  - pwd

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: csye6225-spring2018-sat-lab


notifications:
  email:
    recipients:
    - xue.ti@husky.neu.edu
    - sun.rui@husky.neu.edu
    - chai.yi@husky.edu.edu

