language: java
jdk:
  - oraclejdk8

sudo: true
install: true

script:
  - pwd
  - ls -al
  - mvn clean package -DskipTests
  - cd target/
  - ls -al
  - cd ../
  - pwd
  - ls -al

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - cp infrastructure/aws/codedeploy/*.sh .
  - cp infrastructure/aws/codedeploy/*.yml .
  - mv target/cloudcomputing-0.0.1-SNAPSHOT.war target/ROOT.war
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip target/ROOT.war *.sh *.yml
  - ls -al
  - mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $codedeploy_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: assignment6
  - provider: codedeploy
    access_key_id: $access_key_id
    bucket: $codedeploy_bucket
    key: csye6225-web-app-$TRAVIS_JOB_NUMBER.zip
    bundle_type: zip
    application: $application
    deployment_group: $deployment_group
    region: us-east-1
    secret_access_key: $secret_access_key
    wait-until-deployed: true
    on:
      branch: assignment6
