language: java
jdk:
  - openjdk8


sudo: false
install: true

script:
  - pwd
  - cd webapp/CloudCmpting
  - mvn package
  - mvn test -Dsurefire.useFile=false
  - cd ../..
  - pwd

notifications:
  email:
    recipients:
    - xue.ti@husky.neu.edu
