language: java
jdk:
  - openjdk8


sudo: false
install: true

script:
  - cd webapp/CloudCmpting
  - mvn clean install

branches:
  only:
  - csye6225-spring2018-thur-demo

notifications:
  email:
    recipients:
    - xue.ti@husky.neu.edu
