language: java
jdk:
  - openjdk8


sudo: false
install: true

script:
 - pwd
 - cd webapp/CloudCmpting
 - ls -al
 - mvn clean package install
 - pwd
 - ls -al


notifications:
  email:
    recipients:
    - xue.ti@husky.neu.edu
    - sun.rui@husky.neu.edu
    - chai.yi@husky.edu.edu

