spring:
 jpa:
  database: MYSQL
  show-sql: true
  hibernate:
   ddl-auto: create
   naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
 s:
  prefix: classpath:/templates/
 thymeleaf:
  cache: false
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html